# Generated by Django 4.0.6 on 2022-08-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_watchlist_comment_bid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='urlimg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
